name: Eclectic Dreams
favicon: null
layout_spectrum: 0.75245
typography_spectrum: 0.75363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.03240287071093917
  lightness: 0.10550927557051182
  saturation: 0.7971600433811545
  rhythmicContrast: 0.5
purpose: []
